/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Active': '激活',
    'Age': '年龄:',
    'Beggar': '乞丐',
    'Beggar lvl': '乞丐等级',
    'House': '房子',
    'Holy knight': '圣骑士',
    'Import': '导入',
    'Import/export save': '导入/导出存档',
    'Farmer': '农民',
    'Export': '导出',
    'Evil': '邪恶',
    'Evil control': '邪恶控制',
    'Expense/day': '费用/天',
    'years': '年',
    'Xp/day': '经验/天',
    'xp multipliers': '经验加成',
    'Xp left': '经验剩余',
    'Level': '等级',
    'Library': '图书馆',
    'Mage': '法师',
    'Lifespan': '寿命',
    'Magic': '魔法',
    'Mana control': '法力控制',
    'Master wizard': '精灵法师',
    'Max level': '最高级',
    'Miner': '矿工',
    'Misc': '杂项',
    'Jobs': '工作',
    'Skills': '技能',
    'Shop': '商店',
    'Play': '继续',
    'Pause': '暂停',
    'Personal squire': '私人护卫',
    'Required: ': '要求: ',
    'Reset': '重置',
    'Sapphire charm': '蓝宝石护符',
    'Settings': '设置',
    'Skip': '跳过',
    'Squire': '护卫',
    'Student': '学生',
    'Steel longsword': '钢长剑',
    'Study desk': '书桌',
    'Task': '任务',
    'Toggle': '切换',
    'Touch the eye': '触摸眼球',
    'Wizard': '巫师',
    'Wooden hut': '木屋',
    'Properties': '属性',
    'Progress Knight': '骑士进度条',
    'Small palace': '小宫殿',
    'Strength': '力量',
    'Tent': '帐篷',
    'The Arcane Association': '奥术协会',
    'Veteran footman': '资深步兵',
    'Veteran knight': '资深骑士',
    'Toggle light/dark mode': '切换亮/暗模式',
    'Time warping': '时间扭曲',
    'Amulet': '护身符',
    'Age has caught up to you': '年龄已经赶上了你',
    'Apprentice mage': '学徒法师',
    'Auto-learn': '自动学习',
    'Auto-promote': '自动提升',
    'Book': '书',
    'Chairman': '会长',
    'Combat': '战斗',
    'Cottage': '茅屋',
    'Current job': '当前工作',
    'Current skill': '当前技能',
    'Dark magic': '黑暗魔法',
    'Super immortality': '超级永生',
    'Net/day': '净/天',
    'Muscle memory': '肌肉记忆',
    'Military': '军队',
    'Merchant': '商人',
    'Meditation': '冥想',
    'Large house': '大房子',
    'Knight': '骑士',
    'Join the discord community!': '加入discord社区！',
    'Intimidation': '威胁',
    'Immortality': '永生',
    'Income/day': '收入/天',
    'Homeless': '无家可归',
    'Hard reset game': '硬重置',
    'Grand palace': '大宫殿',
    'Fundamentals': '基本原理',
    'Elite knight': '精英骑士',
    'Effect': '效果',
    'Dumbbells': '哑铃',
    'Day': '天',
    'Dark influence': '邪恶势力',
    'Demon training': '魔鬼训练',
    'Disable warp': '禁用扭曲',
    'Common work': '常规工作',
    'Butler': '男仆',
    'Blood meditation': '血之冥想',
    'Concentration': '专注',
    'Bargaining': '讨价还价',
    'Battle tactics': '战斗战术',
    'Blacksmith': '铁匠',
    'Affects game speed': '影响游戏速度',
    'Affects dark magic xp gain': '影响黑魔法经验收益',
    'Affects all xp gain': '影响所有经验收益',
    'Concentration lvl': '专注等级',
    'evil': '邪恶',
    'Fisherman': '渔夫',
    'Footman': '步兵',
    'Happiness': '幸福',
    'Balance (in coins': '余额 (以硬币计',
    'Legendary knight': '传奇骑士',
    'Farmer lvl': '农民等级',
    'Enable warp': '启用扭曲',
    'Embrace evil': '拥抱邪恶',
    'Demon\'s wealth': '恶魔的财富',
    'Bargaining lvl': '讨价还价等级',
    'Battle tactics lvl': '战斗战术等级',
    'Fisherman lvl': '渔夫等级',
    'Strength lvl': '力量等级',
    'Productivity lvl': '生产力等级',
    'Squire lvl': '护卫等级',
    'Meditation lvl': '冥想等级',
    'Miner lvl': '矿工等级',
    'Veteran knight lvl': '资深骑士等级',
    'Merchant lvl': '商人等级',
    'Footman lvl': '步兵等级',
    'Veteran footman lvl': '资深步兵等级',
    'Knight lvl': '骑士等级',
    'Blacksmith lvl': '铁匠等级',
    'Mana control lvl': '法力控制等级',
    'Muscle memory lvl': '肌肉记忆等级',
    'Elite knight lvl': '精英骑士等级',
    'Student lvl': '学生等级',
    'Mage lvl': '法师等级',
    'Wizard lvl': '巫师等级',
    'Intimidation lvl': '威胁等级',
    'Time warping lvl': '时间扭曲等级',
    'Evil control lvl': '邪恶控制等级',
    'Dark influence lvl': '邪恶势力等级',
    'Chairman lvl': '会长等级',
    'Legendary knight lvl': '传奇骑士等级',
    'Demon training lvl': '魔鬼训练等级',
    'Master wizard lvl': '精灵法师等级',
    'Immortality lvl': '永生等级',
    'Holy knight lvl': '圣骑士等级',
    'Apprentice mage lvl': '学徒法师等级',
    'Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped with the finest gear. Such a feared unit on the battlefield is paid extremely well.': '用最精良的装备，一次歼灭敌军中队。这样一支令人敬畏的部队在战场上的薪水非常高。',
    'Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.': '比普通的房子大得多，普通的房子有更多的房间和多层。这栋建筑很宽敞，但价格不菲。',
    'Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?': '用魔法延长你的寿命。然而，这真的是你一直在寻找的永生吗?',
    'Create and revise battle strategies, improving experience gained in the military.': '创建和修改作战策略，提高在军队中获得的经验。',
    'Condition your body and strength through harsh training. Stronger individuals are paid more in the military.': '通过艰苦的训练来调节你的身体和力量。更强壮的人在军队中得到更多的报酬。',
    'Collapse entire armies in mere seconds with your magically imbued blade. The handful of elite knights who attain this level of power are showered with coins.': '用你的魔法剑在几秒钟内瓦解整个军队。少数精英骑士获得这个等级的权力会得到大量的金币。',
    'Carry around your knight\'s shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.': '带着你骑士的盾牌和剑沿着战场行进。工资很低，但工作经验很有价值。',
    'Plow the fields and grow the crops. It\'s not much but it\'s honest work.': '犁地，种庄稼。这工作不多，但很正经。',
    ', which will heavily impact your future lives.': '，这将严重影响你们未来的生活。',
    'Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.': '深入危险的洞穴，开采有价值的矿石。与所涉及的风险相比，报酬是相当少的。',
    'Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.': '用邪恶赋予你的强大力量包围你自己，让你轻松地获得和吸收任何工作或技能。',
    'Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.': '镶嵌在一颗罕见的蓝宝石上，这个咒语激活你体内更多的魔法通道，让你更容易学习魔法。',
    'Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.': '通过其他生物的牺牲来成长和培养你内在的邪恶，急剧增加邪恶收益。',
    'Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.': '在剧烈运动中用来比以前更快地增强和积累力量的重型工具。',
    'Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.': '让你的家庭随时保持清洁，每天还准备三顿美味的饭菜，让你在一个更快乐，无压力的心情。',
    'Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.': '学会散发一种恶魔的气息，打击其他商家的极度恐惧，迫使他们给你很大的折扣。',
    'Learn to procrastinate less at work and receive more job experience per day.': '学会在工作中减少拖延，每天积累更多的工作经验。',
    'Productivity': '生产力',
    'Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.': '放下你的生命与敌人的士兵战斗。一份勇敢，体面的工作但你在这个宏伟的计划中仍然毫无价值。',
    'Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.': '钓上各种各样的鱼，然后把它们卖成一把硬币。一份轻松但收入微薄的工作。',
    'Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn\'t very pleasant.': '破烂的原木和肮脏的干草和马粪粘在一起。虽然比帐篷坚固多了，但是臭气也不太好闻。',
    'Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.': '从头到脚都裹着钢铁，轻松地刺穿敌军士兵。一份报酬丰厚、非常体面的工作。',
    'Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.': '睡在不舒服、肮脏的街道上，每天晚上几乎冻死。不会比这更糟了。',
    'Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.': '为军队冶炼矿石，精心锻造武器。一份体面的、报酬不错的普通工作。',
    'Something tells you that the amulet might transform even further after living for': '直觉告诉你，在你完成了第一次重生之后，如果你的年龄（当前年龄，不是寿命上限）超过200岁，这个护身符还可能会带来更大的变化',
    'Spend your days administrating The Arcane Association and investigate the concepts of true immortality. The chairman receives ludicrous amounts of pay daily.': '花时间管理你的神秘协会和调查的概念，真正的永生。会长每天收到的薪水多得可笑。',
    'Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.': '学习法术力理论并练习基本法术。 可以支付生活费用的少量薪水，但是，这是成为法师的必经阶段。',
    'Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.': '昼夜不停地挣扎着几个铜币。 感觉就像您每天都处在死亡边缘。',
    'Strengthen your neurons through habit and repetition, improving strength gains throughout the body.': '通过习惯和重复来强化你的神经元，改善全身力量的增强。',
    'Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.': '用木框架和茅草屋顶建造的。以公平的价格提供体面的生活条件。',
    'Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.': '加强你全身的魔法通道，帮助你成为一个更强大的魔法使用者。',
    'Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.': '储存了大量的书籍，每一本都包含了大量的信息，从基本的生活技能到复杂的魔法咒语。',
    'for your jobs and skills equivalent to': '对你的工作和技能，加成的公式为',
    'Fill your mind with peace and tranquility to tap into greater happiness from within.': '让你的头脑充满和平与安宁，从内心发掘更大的幸福。',
    'Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.': '让全世界都感到恐惧，一眨眼的功夫就把整个国家都毁灭了。大约每个世纪，只有一位神圣骑士配得上这样一个受人尊敬的头衔。',
    'A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.': '一座完全由金银构成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。',
    'A fine blade used to slay enemies even quicker in combat and therefore gain more experience.': '在战斗中可以更快地杀死敌人，从而获得更多经验。',
    'A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.': '仅仅是人的身体就太软弱无力，无法抵挡邪恶。用禁止的方法训练，慢慢变成一个能够快速吸收知识的恶魔。',
    'A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.': '一个写下你所有想法和发现的地方，让你学得更快。',
    'A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.': '一张由两根软弱的木棒托着的破布。生活条件很糟糕，但至少你有个栖身之所。',
    'A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.': '一个非常丰富和精心建造的结构，镶有精细的金属，如银。维持奢华的生活方式需要极高的费用。',
    'Assists you in completing day to day activities, giving you more time to be productive at work.': '帮助你完成每天的活动，给你更多的时间在工作中更有效率。',
    'Bend space and time through forbidden techniques, resulting in a faster gamespeed.': '通过禁止的技术扭曲空间和时间，导致更快的游戏速度。',
    'Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.': '拥有无与伦比的天赋，可以随心所欲地施展难以置信的魔术。据说巫师大师拥有足够的破坏力，足以将一个帝国从地图上抹去。',
    'More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.': '比普通步兵更有经验，更有用，在战斗中用你的力量消灭敌人。(工资没那么低。)',
    'Study the tricks of the trade and persuasive skills to lower any type of expense.': '学习交易技巧和说服技巧来降低任何类型的费用。',
    'Tame the raging and growing evil within you, improving evil gain in-between rebirths.': '驯服你内心的愤怒和增长的邪恶，在转世之间提高邪恶增益。',
    'This means you will learn everything again much more quickly than you did in your previous life.': '这意味着你学习每一件事的速度要比你以前更快。',
    'Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.': '通过利用古老的、被禁止的技术，将你的寿命大大延长到无法理解的程度。',
    'Through the means of dark magic, multiply the raw matter of the coins you receive from your job.': '通过黑魔法，将您从工作中获得的硬币的原始物质相乘。',
    'Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.': '从一个城镇到另一个城镇，以物易物。这份工作报酬不错，而且不需要太多的体力劳动。',
    'Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.': '通过施放中间法术和指导其他学徒来扭转战斗的趋势。这份工作的报酬非常高。',
    'Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.': '在法师的指导下，在战斗中对敌人施展基本法术。将提供相当数量的工资以支付生活费用。',
    'Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.': '使用先进的法术来蹂躏和摧毁整个军团的敌人士兵。只有一小部分的法师配得上这个角色，并能得到高得离谱的报酬。',
    'Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.': '利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队里的大多数男仆都不可能得到这样一份报酬优厚的工作。',
    'Your age has met your lifespan, use the amulet to rebirth before you pass away': '你的年龄已经达到了你的寿命，用护身符在你死前重生',
    'Improve your learning speed through practising intense concentration activities.': '通过练习集中注意力的活动来提高你的学习速度。',
    'A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.': '一个专门的区域，提供了许多精致的文具和装备设计，以促进您的研究进展。',
    'A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.': '用石头、砖和坚固的木材建造的建筑，里面有几个房间。虽然很贵，但这是一个舒适的住所。',
    "Save to file": "保存到文件",
    "Scales Of Thought": "思想天平",
    "Secret": "秘密",
    "Senior": "高级",
    "Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn't very pleasant.": "破旧的原木和肮脏的干草与马粪粘在一起。然而，比帐篷坚固得多，恶臭不是很令人愉快。",
    "Shop": "商店",
    "Skills": "技能",
    "Skip": "跳过",
    "Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.": "轻而易举地砍杀并刺穿敌方士兵，同时从头到脚全身覆盖着钢铁。一份体面的薪水和非常受人尊敬的工作。",
    "Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.": "睡在不舒服、肮脏的街道上，每晚都几乎冻死。不能比这更糟了。",
    "Small Field": "小田地",
    "Small Manor": "小庄园",
    "Small palace": "小宫殿",
    "Small Shop": "小店",
    "Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.": "为军队冶炼矿石并精心打造武器。一份受人尊敬且报酬还可以的平民工作。",
    "Something tells you that the amulet might transform even further after living for": "有人告诉你，护身符可能会在生活后进一步转变",
    "Soon!": "很快！",
    "Sophomore": "二年级",
    "Squire": "乡绅",
    "Steel longsword": "钢长剑",
    "Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.": "存放着一系列书籍，每本书都包含从基本生活技能到复杂魔法的大量信息。",
    "Strength": "力量",
    "Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.": "加强你全身的法力通道，帮助你成为更强大的魔法使用者。",
    "Strengthen your neurons through habit and repetition, improving strength gains throughout the body.": "通过习惯和重复来增强你的神经元，提高整个身体的力量增益。",
    "Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.": "结构为木框架和茅草屋顶。以合理的价格提供体面的生活条件。",
    "Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.": "为几枚铜币日夜奋斗。感觉就像你每天都在死亡的边缘。",
    "Student": "学生",
    "Study desk": "书桌",
    "Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.": "学习法力理论并练习基本法术。支付生活费用的报酬很少，但是，这是成为法师的必要阶段。",
    "Study the tricks of the trade and persuasive skills to lower any type of expense.": "研究交易技巧和说服技巧以降低任何类型的费用。",
    "Super immortality": "超级不朽",
    "Tame the raging and growing evil within you, improving evil gain in-between rebirths.": "驯服你内心肆虐和增长的邪恶，提高重生之间的邪恶收益。",
    "Task": "任务",
    "Tent": "帐篷",
    "The Arcane Association": "奥术协会",
    "The finest $3 pizza modern food science can conceive": "现代食品科学能想到的最好的 3 美元比萨饼",
    "The nobility cares not for your tooltip desires.": "贵族不在乎你的工具提示欲望。",
    "The Order of Discovery": "发现秩序",
    "The potential routes of experimentation are infinite. The questions, limitless. What should a budding Chairman focus on in order to enhance their knowledge of both life and magic? In medieval times, biology is limited by the tools of the time. Without microscopes and advanced chemistry, it is almost impossible to fully grasp the concept of cellular life and the underlying mechanisms governing DNA, metabolism, and degradation of biological structures. Magical Engineering is a worthy pursuit for a Chairman looking to use Magic to build the tools of future scientific inquiry.": "潜在的实验路线是无限的。问题，无穷无尽。一个崭露头角的主席应该关注什么来增强他们对生命和魔法的了解？在中世纪，生物学受到当时工具的限制。没有显微镜和先进的化学，几乎不可能完全掌握细胞生命的概念以及控制 DNA、代谢和生物结构降解的潜在机制。对于希望使用魔法来构建未来科学探究工具的主席来说，魔法工程是一项值得追求的目标。",
    "This means you will learn everything again much more quickly than you did in your previous life.": "这意味着您将比前世更快地再次学习所有内容。",
    "This sweet chestnut horse will haul you and your trade goods to distant cities where your novel fabrics and knick knacks will fetch a tidy profit.": "这匹甜美的栗色马会将您和您的贸易货物拖到遥远的城市，在那里您的新颖面料和小摆设将获得可观的利润。",
    "Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.": "通过利用古老的禁忌技术，大大延长你的寿命，超出你的理解。",
    "Through Magical Biology, a Chairman seeks to leverage their new inventions and new frames of thought to directly probe, change, experiment and observe the effects of magic on various cellular structures to enhance their vitality and vigor. Magical Biology is the final step towards immortality.": "通过魔法生物学，主席试图利用他们的新发明和新思维框架来直接探索、改变、实验和观察魔法对各种细胞结构的影响，以增强他们的活力和活力。神奇生物学是迈向永生的最后一步。",
    "Through the means of dark magic, multiply the raw matter of the coins you receive from your job.": "通过黑魔法的手段，倍增你从工作中获得的硬币的原材料。",
    "Time warping": "时间扭曲",
    "Toggle": "切换",
    "Toggle light/dark mode": "切换亮/暗模式",
    "Touch the eye": "触摸眼睛",
    "Town": "小镇",
    "Town Income per day": "城镇每天收入",
    "Trade Psychology": "贸易心理学",
    "Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.": "从一个城镇到另一个城镇旅行，以物易物。这项工作的薪水不错，而且人工密集程度要低得多。",
    "Try as I do, these temporary tooltips are poo.": "像我一样尝试，这些临时工具提示很糟糕。",
    "Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.": "通过施展中级法术和指导其他学徒扭转战局。这项特殊工作的薪水非常高。",
    "Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.": "在法师的监督下，对战斗中的敌人施展基本法术。将提供丰厚的报酬以支付生活费用。",
    "Unusual Insight": "不寻常的洞察力",
    "Up to this point, a Chairman's experience with Magic is almost entirely on the human scale. A budding apprentice learns to extend the life of a flower. A mage learns to incinerate man, horse, and siege engine. Master Wizards learn to shake the earth and obscure the vision of their human opponents with natural phenomena and magic alike. A Chairman must learn to shift their focus from the scale of humanity to both higher highs and lower lows. A Chairman seeking immortality must investigate the smallest structures of existence, must continue probing deeper and uncovering astounding knowledge and even more astounding questions. Scales of Thought will enhance Mana Control and Chairman experience gain rates by a substantial rate. By probing nature on a deeper level, a Chairman gains unparalleled understanding which influences every magical action pursuit.": "到目前为止，主席对万智牌的体验几乎完全是在人的范围内。一个初出茅庐的学徒学习延长一朵花的寿命。法师学会焚烧人、马和攻城车。法师大师学会用自然现象和魔法来震动地球并模糊他们人类对手的视野。主席必须学会将他们的注意力从人性的尺度转移到更高的高度和更低的低点。一个追求长生不老的主席，必须研究最小的存在结构，必须继续深入探索，发现惊人的知识，甚至更惊人的问题。思想规模将显着提高法力控制和主席经验获取率。通过在更深层次上探索自然，主席获得了无与伦比的理解力，这种理解力影响着每一个神奇的行动追求。",
    "Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.": "利用先进的法术蹂躏和摧毁敌方士兵的整个军团。只有一小部分法师配得上这个角色，并获得高得离谱的报酬。",
    "Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.": "利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队中的大多数步兵永远无法获得如此高薪的工作。",
    "Veteran footman": "资深男仆",
    "Veteran knight": "资深骑士",
    "Vice Count": "副伯爵",
    "Weapon Outlet": "武器出口",
    "With your newfound land and tools, you've become relatively wealthy. For a peasant farmer, at least. Tale of your achievements has reached the ears of the local lord, who has granted permission for you to rent one of his oxen plow teams and associated gear.": "有了新发现的土地和工具，你变得相对富有。至少对于农民来说。你的成就传到了当地领主的耳中，他允许你租用他的一个牛犁队和相关装备。",
    "Witty placeholder, my name is.": "机智的占位符，我的名字是。",
    "Wizard": "巫师",
    "Wooden hut": "木屋",
    "Wooden Hut": "木屋",
    "Writers pour their souls into the written word. Your extensive reading combined with your countless years spent interacting with people have lent you unparalleled insight into the way mankind views the positive and the negative events of this world. An ethical scholar would refrain from abusing this knowledge for financial gain.": "作家将他们的灵魂倾注在文字中。您的广泛阅读加上您与人交往的无数年，让您对人类看待这个世界的积极和消极事件的方式有了无与伦比的洞察力。伦理学者会避免滥用这些知识谋取经济利益。",
    "Xp left": "经验剩余",
    "xp multipliers": "经验乘数",
    "Xp/day": "经验/天",
    "years": "年",
    "You found this cracked fishing rod partially buried by the shore. It needs some major TLC, but it'll help you reel in bigger fish.": "你发现这根破裂的钓鱼竿部分被岸边掩埋。它需要一些主要的 TLC，但它会帮助你钓到更大的鱼。",
    "You stumble across a strange looking amulet on your 25th birthday. It does not look like\n                            it has any worth on the market given that it's made from cheap-looking copper. However, you\n                            feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.": "你在 25 岁生日时偶然发现了一个看起来很奇怪的护身符。它看起来不像\n 它在市场上没有任何价值，因为它是由看起来很便宜的铜制成的。但是，您\n 有一种保留护身符的奇怪冲动，因此您将其放入口袋以妥善保管。",
    "You're pretty sure this lumpy hunk of iron used to be someone's chamber pot.": "你很确定这块块状的铁块曾经是某人的夜壶。",
    "Your age has met your lifespan, use the amulet to rebirth before you pass away": "你的年龄已经到了你的寿命，在你去世之前使用护身符重生",
    "Your first shop. This cozy storefront lies on the main street of a medium-sized walled town. Commoners, nobles, and military patrols all pass along this street, so at the very least people will know your store exists.": "你的第一家店。这家舒适的店面位于一个中型围城的主要街道上。平民、贵族和军事巡逻队都在这条街上经过，所以至少人们会知道你的商店存在。",
    "Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n                                A mouth emerges from its surface and begins to cackle, and proceeds to say: \"So you've made it this far... Are you ready to embrace evil?\"": "你的直觉是对的。在您达到 200 岁的那一刻，您会听到护身符发出不祥的嗡嗡声。\n 一张嘴从它的表面露出并开始咯咯地笑，然后继续说：“所以你已经做到了这一步...... . 你准备好拥抱邪恶了吗？\"",
    "Your heroic feats in battle have earned you a title of nobility and a huge swath of some rather...undesirable land. \n                        Your territory is hundreds of miles from the nearest village, the soil is infertile, and the few living beings around are bandits and hermits. It's going to \n                        take a lot of work to make this place worth anything.": "你在战斗中的英勇壮举为你赢得了贵族头衔和一大片相当……不受欢迎的土地。 \n 你的领地距离最近的村庄数百里，土质贫瘠，周围为数不多的生灵是土匪和隐士。 \n 要让这个地方物有所值，需要做很多工作。",
    "Your leadership of the caretaking team has proven you have a modicum of brain cells. A teacher you frequently see has vouched for your potential. Your studies are long and often boring, but you can sense there are great secrets within these halls waiting to be discovered.": "你对看护团队的领导已经证明你有少量的脑细胞。你经常见到的一位老师已经证明了你的潜力。你的学习时间很长，而且常常很无聊，但你能感觉到这些大厅里有很多秘密等待被发现。",
    "Your people won't become spoiled while living in huts such as these; they'll be one with nature.": "住在这样的小屋里，你的人民不会被宠坏；他们将与自然合而为一。",
    "Your rising status has granted you access to a small countryside manor. With the manor comes two hundred acres of farmland and the associated serfs, grain mill, and a small river for irrigation. The attendant tells you of a beautiful hollow in some nearby woods where you can relax and meditate.": "您不断上升的地位使您可以进入一个小乡村庄园。庄园里有两百英亩的农田和相关的农奴、磨坊和一条用于灌溉的小河。服务员告诉您在附近的一些树林里有一个美丽的空洞，您可以在那里放松和冥想。",
    "Your training in the more mundane affairs of the non-magical world have developed your critical analysis skills. As you gain knowledge, magical concepts which seemed inscrutable and mysterious are becoming more relatable to the physical world around you.": "你在非魔法世界更平凡事务中的训练培养了你的批判性分析技能。随着你获得知识，那些看似神秘莫测的魔法概念正变得与你周围的物理世界更加相关。",
    "Fill your mind with peace and tranquility to tap into greater happiness from within.": "让你的心灵充满平静与安宁，从内心获得更大的幸福。",
    "Fisherman": "渔夫",
    "Flow": "流动",
    "Footman": "步兵",
    "for your jobs and skills equivalent to": "你的工作和技能相当于",
    "Forget me not, for this author shall not.": "不要忘记我，因为这位作者不会。",
    "Freshman": "大一新生",
    "Fundamentals": "基础知识",
    "Go outside.": "出去。",
    "Good.": "好的。",
    "Grain Shed": "粮棚",
    "Grand Duke": "大公",
    "Grand palace": "大宫殿",
    "Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.": "通过牺牲其他众生来培养和培养你内心的邪恶，大大增加邪恶的收益。",
    "Happiness": "幸福",
    "Hard reset game": "硬重置游戏",
    "Having completed your basic studies, the Order grants you a bottom-of-the-barrel position as research associate to an old member of little renown. Any major misstep will probably result in your banishment from the halls of knowledge.": "完成基础学习后，骑士团授予您一个底层职位，担任一位名不见经传的老成员的研究助理。任何重大失误都可能导致你被逐出知识殿堂。",
    "Healing the soil is a monumental undertaking. It will doubtless take generations of care. Or some nifty magic...": "修复土壤是一项艰巨的任务。毫无疑问，它需要几代人的照顾。或者一些漂亮的魔法......",
    "Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.": "用于剧烈运动的重型工具比以前更快地增强和积累力量。",
    "High King": "至高王",
    "High Lord": "大领主",
    "Holy knight": "圣骑士",
    "Homeless": "无家可归",
    "House": "房子",
    "Idle citizens: 0": "闲散市民：0",
    "If you decide to embrace evil, there is a price. All of your levels, coins and even max levels will be reset.\n                                Your town will be utterly annihilated; your townspeople slaughtered by your own hand.\n                                You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain": "如果你决定拥抱邪恶，那是有代价的。你所有的等级、金币甚至最高等级都将被重置。\n你的城镇将被彻底歼灭；你的镇民被你亲手屠杀。\n你将重生为新的石板。但是，您将解锁新的技能线并获得",
    "Illustrious Chairman": "杰出的主席",
    "Immortality": "不朽",
    "Import/export save": "导入/导出保存",
    "Improve your learning speed through practising intense concentration activities.": "通过练习集中注意力的活动来提高您的学习速度。",
    "Income/day": "收入/天",
    "Intense bouts of concentration warp your perception of time": "强烈的注意力会扭曲你对时间的感知",
    "Intimidation": "恐吓",
    "Is it April 20th?": "是4月20日吗？",
    "It's poo.": "是便便。",
    "Jobs": "工作",
    "Join the discord community!": "加入不和谐社区！",
    "Junior": "初级",
    "Junior Caretaker": "初级看护人",
    "Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.": "让您的家庭时刻保持清洁，每天还准备三顿可口的饭菜，让您拥有更快乐、无压力的心情。",
    "King": "国王",
    "Knight": "骑士",
    "Large house": "大房子",
    "Lead Caretaker": "主要管理员",
    "Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.": "学会散发出令其他商人极度恐惧的恶魔气息，迫使他们给你大量折扣。",
    "Learn to procrastinate less at work and receive more job experience per day.": "学会在工作中减少拖延，每天获得更多的工作经验。",
    "Legendary knight": "传奇骑士",
    "Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?": "通过魔法延长你的寿命。然而，这真的是你努力寻求的不朽吗……？",
    "Level": "等级",
    "Library": "图书馆",
    "Lifespan": "寿命",
    "Livestock-derived Fertilizer": "畜禽肥料",
    "Load from file": "从文件加载",
    "Lord": "领主",
    "Mage": "法师",
    "Magic": "魔法",
    "Magical Biology": "神奇生物学",
    "Magical Engineering": "魔法工程",
    "Mana control": "法力控制",
    "Master of life and war. Renowned throughout the magical and non-magical worlds alike, an Illustrious Chairman is completely free to follow their own path of discovery and ambition. On the other hand, there is that curious note to investigate...": "生活与战争的大师。赫赫有名的主席在魔法和非魔法世界都享有盛誉，他完全可以自由地追随自己的探索和野心之路。另一方面，有一个奇怪的笔记需要调查......",
    "Master wizard": "大师级巫师",
    "Max level": "最高等级",
    "Meditation": "冥想",
    "Merchant": "商人",
    "Military": "军队",
    "Mind": "思想",
    "Miner": "矿工",
    "Miner's Lantern": "矿工灯笼",
    "Misc": "杂项",
    "More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.": "比普通步兵更有经验和有用，在战斗中用你的力量消灭敌军。工资没那么差。",
    "Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.": "比拥有更多房间和多层楼的普通房子大得多。该建筑非常宽敞，但价格却很高。",
    "Muscle memory": "肌肉记忆",
    "Net/day": "净/天",
    "Nobility": "贵族",
    "Note: Your town's abuse of the grain markets has been noted. Expect the kingdon to limit your egregious profits soon.": "注意：您所在城镇滥用粮食市场的行为已被注意到。期待国王很快限制你的巨额利润。",
    "Novel Knowledge": "新知识",
    "Now to find yourself a nice Queen. Or two. Or three.": "现在给自己找一个漂亮的女王。或者两个。或三个。",
    "Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped with the finest gear. Such a feared unit on the battlefield is paid extremely well.": "以非凡的熟练度一口气消灭敌方士兵的中队，同时配备最好的装备。战场上这样一个令人恐惧的单位，薪水非常好。",
    "Oh lord, please let Gottmilk write the real tooltips already. These are too painful to endure.": "哦，上帝，请让 Gottmilk 写出真正的工具提示。这些太痛苦了，无法忍受。",
    "On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n                            out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n                            a strange etching on the centre of the amulet.": "在您 45 岁生日时，您会感到口袋里的护身符不受控制地颤抖。你把它拿出来，不断的颤抖突然停止了。更令您惊讶的是，您注意到护身符中心有一个奇怪的蚀刻。",
    "On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n                                amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n                                you realise you do not have many years to live left anyway so you consider touching the eye\n                                to see what happens.": "在您的 65 岁生日那天，您再次遇到\n 护身符奇怪的、无法解释的颤抖。但这一次，一个活生生的眼球从中心出现。虽然非常害怕，\n你意识到你已经没有多少年可以活了，所以你考虑触摸眼睛\n看看会发生什么。",
    "Ox-driven Plow": "牛驱犁",
    "Pack Horse": "驮马",
    "Pause": "暂停",
    "Personal squire": "个人侍从",
    "Plow the fields and grow the crops. It's not much but it's honest work.": "耕种田地，种植庄稼。这不是很多，但它是诚实的工作。",
    "Probation": "试用期",
    "Productivity": "生产率",
    "Progress Knight - Reborn": "进步骑士 - 重生",
    "Projects": "项目",
    "Properties": "特性",
    "Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.": "放下你的生命与敌方士兵战斗。一份勇敢、受人尊敬的工作，但在宏伟的计划中你仍然一文不值。",
    "Rag Clothing": "抹布服装",
    "Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.": "卷入各种鱼并以少量硬币出售。一份轻松但收入仍然很低的工作。",
    "Required: ": "要求：",
    "Research": "研究",
    "Reset": "重置",
    "Rhyming is crime-ing, and feature delay is not the way.": "押韵是犯罪，功能延迟不是办法。",
    "Rocks abound within these sour patches of inhospitable soil you and your people call \"farms\".": "在你和你的人民称之为“农场”的这些荒凉的土壤中，岩石比比皆是。",
    "Sapphire charm": "蓝宝石吊饰",
    ", which will heavily impact your future lives.": "，这将严重影响你未来的生活。",
    "1 + the max level of the skill or job / 10.": "1 + 技能或工作的最高等级 / 10。",
    "2 whole centuries": "2 整个世纪",
    "A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.": "由石砖和坚固的木材组成的建筑物，其中包含几个房间。虽然很贵，但是住的很舒服。",
    "A busy military means a busy weapons store. One of the liuetenants who frequents your small shop recently let slip that a long military campaign is imminent. Naturally, a savy merchant such as yourself sees the business opportunity provided by war.": "忙碌的军队意味着忙碌的武器商店。最近经常光顾您的小商店的一位中尉透露，一场漫长的军事行动迫在眉睫。像您这样精明的商人自然会看到战争带来的商机。",
    "A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.": "一个专门的区域，提供许多精美的文具和设备，旨在促进您的研究进展。",
    "A fine blade used to slay enemies even quicker in combat and therefore gain more experience.": "用于在战斗中更快地杀死敌人并因此获得更多经验的精美刀片。",
    "A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.": "一座完全由金银组成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。",
    "A humble dwelling that provides the basic requirements of nature. \n                            Rough wooden logs join together in support of brown thatched roofing, providing a cozy retreat from rain and wind.": "提供自然基本要求的简陋住宅。 \n 粗糙的原木连接在一起，支撑着棕色的茅草屋顶，提供了一个舒适的避风港避风港。",
    "A low-level administrator of the ancient Order of Discovery has offered you a job. Cleaning shit-stained chamber pots and mopping kitchen floors isn't glamorous work, but it gives you the rare chance to peruse the Order's world-class library of exotic books. Who cares if touching the books is an offense worthy of expulsion?": "古代发现勋章的一位低级管理员为您提供了一份工作。清洁脏兮兮的夜壶和拖地厨房地板并不是一件光鲜亮丽的工作，但它让您有难得的机会细读骑士团世界级的异国书籍图书馆。谁在乎触摸书籍是否是值得开除的罪行？",
    "A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.": "单纯的人体实在是太虚弱无力，无法抵挡邪恶。修炼禁法，慢慢化身为魔，快速吸收知识。",
    "A mind needs training. Your time spent absorbing new ideas and worldviews has increased your ability to assimilate new ideas and make connections between seemingly unrelated concepts.": "头脑需要训练。你花在吸收新想法和世界观上的时间提高了你吸收新想法和在看似不相关的概念之间建立联系的能力。",
    "A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.": "一个写下你所有想法和发现的地方，让你学得更快。",
    "A savy merchant knows the dynamics of supply and demand. Besides the obvious fact that storing your grain delays that pesky nuisance of winter starvation,\n                            your grain sheds allow your townsfolk to hold off selling their grain until prices rise. The more grain storage your town builds, the more influence on prices\n                            your town wields.": "精明的商人了解供需动态。除了储存谷物可以延缓令人讨厌的冬季饥饿问题这一显而易见的事实之外，\n 您的谷物棚让您的城镇居民可以推迟出售谷物，直到价格上涨。您的城镇建立的粮食储存越多，对您城镇的价格的影响就越大。",
    "A set of rusty iron tools to help loosen soil, shape wood, and attach things. Where did you even find this junk?": "一套生锈的铁工具，用于帮助松土、塑造木头和连接东西。你在哪里找到这个垃圾？",
    "A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.": "几根软弱的木棍支撑着一块破布。糟糕的生活条件，但至少你有一个屋顶。",
    "A tooltip, a thought. Helpful, I am not.": "一个工具提示，一个想法。有帮助，我没有。",
    "A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.": "一个非常丰富且精心打造的结构，边缘镶有银等精美金属。维持奢侈生活方式的费用极高。",
    "Active": "积极的",
    "Affects all xp gain": "影响所有经验增益",
    "Affects dark magic xp gain": "影响黑魔法的经验值增益",
    "Affects game speed": "影响游戏速度",
    "After a pitched battle between bickering barons, your fellow farmer lost his leg and two eldest sons. With a wife and small children to take care of, he says he'll entrust his land to you in exchange for using the proceeds to take care of his family.": "在争吵不休的贵族之间展开激战后，你的农民同伴失去了一条腿和两个长子。有妻子和小孩要照顾，他说他会把他的土地交给你，以换取用收益来照顾他的家人。",
    "After weeks of feeling your way through pitch black tunnels, bandaging scraped hands, and getting smacked in the face by your fellow miner's pickaxes, you have the bright idea to purchase a lantern. Hopefully some light will help illuminate additional mineral deposits and geological phenomena.": "经过数周的摸索穿过漆黑的隧道，包扎擦伤的手，并被你的矿工的镐打在脸上，你有了购买灯笼的好主意。希望一些光线将有助于照亮更多的矿藏和地质现象。",
    "After weeks of freezing on the streets, you're making enough money to buy some cheap clothes. They're not much, but they'll keep you warm enough to focus.": "在街上冻了几个星期之后，你赚到了足够的钱买一些便宜的衣服。它们并不多，但它们会让你保持足够的温暖以集中注意力。",
    "Age": "年龄",
    "Age has caught up to you": "年龄已经赶上了你",
    "Amulet": "护身符",
    "Apprentice mage": "学徒法师",
    "Arch Duke": "大公爵",
    "Are these placeholder tooltips infuriating?": "这些占位符工具提示是否令人愤怒？",
    "As you walk amongst your fellow Master Wizards, who in recognition of your vast power have just elected you Chairman of the Arcane Association, you receive this anonymous note: \"We have followed your progress with great interest. Many have walked this path, but few have used the amulet you now wear to its full potential. But you are not the first to make it this far. Strive on. We will contact you, when the time is right.\"": "当你走在你的法师大师们中间，他们对你巨大的力量的认可刚刚选举你为奥术协会主席，你会收到这样一封匿名信：“我们怀着极大的兴趣关注着你的进步。很多人都走过这条路，但很少有人将你现在佩戴的护身符发挥其全部潜力。但你并不是第一个做到这一点的人。继续努力。我们会在适当的时候与你联系。\"",
    "Assists you in completing day to day activities, giving you more time to be productive at work.": "帮助您完成日常活动，让您有更多时间在工作中高效工作。",
    "Auto-learn": "自动学习",
    "Auto-promote": "自动推广",
    "Balance (in coins": "余额（硬币",
    "Bargaining": "讨价还价",
    "Baron": "男爵",
    "Baronet": "男爵",
    "Basic Buildings": "基本建筑",
    "Basic Farm Tools": "基本农具",
    "Battle tactics": "战斗战术",
    "Because Viscount sounds gross.": "因为子爵听起来很恶心。",
    "Beggar": "乞丐",
    "Bend space and time through forbidden techniques, resulting in a faster gamespeed.": "通过禁忌技巧弯曲空间和时间，从而加快游戏速度。",
    "Blacksmith": "铁匠",
    "Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.": "拥有无与伦比的天赋，随心所欲地用魔法完成令人难以置信的壮举。据说巫师大师的破坏力足以将一个帝国从地图上抹去。",
    "Blood meditation": "血液冥想",
    "Book": "书",
    "Breech Bellows": "后膛波纹管",
    "Build": "建造",
    "Butler": "男管家",
    "By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n                                However, you will gain": "触摸眼球，你将重生，必须重新开始生活，失去所有等级和硬币。\n但是，你会获得",
    "Carry around your knight's shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.": "在战场上随身携带骑士的盾牌和剑。工资很低，但工作经验很有价值。",
    "Chairman": "主席",
    "Cheap Fishing Rod": "便宜的钓鱼竿",
    "Cobbled together with two sticks and a pair of old trousers, this tool boosts the heat and efficiency of your forge.": "用两根木棍和一条旧裤子拼凑而成，这个工具可以提高锻造的热量和效率。",
    "Collapse entire armies in mere seconds with your magically imbued blade. The handful of elite knights who attain this level of power are showered with coins.": "用你的魔法剑在几秒钟内瓦解整个军队。少数获得这种力量的精英骑士会得到大量硬币。",
    "Combat": "战斗",
    "Common work": "共同工作",
    "Concentration": "专注",
    "Condition your body and strength through harsh training. Stronger individuals are paid more in the military.": "通过严格的训练来调节你的身体和力量。更强壮的人在军队中的报酬更高。",
    "Cottage": "茅屋",
    "Count": "伯爵",
    "Crappy Anvil": "蹩脚的铁砧",
    "Create and revise battle strategies, improving experience gained in the military.": "创建和修改战斗策略，提高在军队中获得的经验。",
    "Current job": "当前工作",
    "Current skill": "当前技能",
    "Dark influence": "黑暗的影响",
    "Dark magic": "黑暗魔法",
    "Day": "日",
    "Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.": "深入危险的洞穴并开采有价值的矿石。与所涉及的风险相比，报酬相当微薄。",
    "Demon training": "恶魔训练",
    "Demon's wealth": "恶魔的财富",
    "Duke": "公爵",
    "Dumbbells": "哑铃",
    "Effect: Additional 6% Farm income (compounding)": "效果：额外 6% 的农场收入（复合）",
    "Effect: Additional daily income: 150 coppers": "效果：每日额外收入：150铜币",
    "Effect: None": "效果：无",
    "Elite knight": "精英骑士",
    "Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.": "这款护身符嵌入了稀有蓝宝石，可激活体内更多的法力通道，让学习魔法更加轻松。",
    "Embrace evil": "拥抱邪恶",
    "Emperor of Mankind": "人类皇帝",
    "Enable warp": "启用扭曲",
    "Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.": "用邪恶赋予你的强大力量包围自己，让你轻松掌握和吸收任何工作或技能。",
    "Even grander than the most grand Grand Duke your granddad could....Grand.": "甚至比你祖父所能做到的最伟大的大公还要伟大……伟大。",
    "Even higher. Even nobler.": "更高。 甚至更高贵。",
    "evil": "邪恶",
    "Evil": "邪恶",
    "Evil control": "邪恶控制",
    "Expense/day": "费用/天",
    "Farm": "农场",
    "Farmer": "农民",
    "Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.": "举世畏惧，眨眼间灭尽万国。 几乎每个世纪，只有一位圣骑士配得上如此尊贵的称号。",
    "Cost": "成本",
    "Idle citizens": "空闲市民",
    "Effect: Additional 6% Farm income (compounding": "效果:增加6%的农场收入(复利",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //原样
    '2 whole centuries': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n                            ": "\n                            ",
    "Battle tactics level ": "战斗战术等级 ",
    "Veteran knight level ": "资深骑士等级 ",
    "Strength level ": "力量等级 ",
    "Farmer level ": "农民等级 ",
    "Productivity level ": "生产力等级 ",
    "Concentration level ": "专注等级 ",
    "Beggar level ": "乞丐等级 ",
    "Miner level ": "矿工等级 ",
    "Fisherman level ": "渔夫等级 ",
    "Meditation level ": "冥想等级 ",
    "Squire level ": "护卫等级 ",
    "Veteran footman level ": "资深步兵等级 ",
    "Elite knight level ": "骑士等级 ",
    "Knight level ": "骑士等级 ",
    "Holy knight level ": "圣骑士等级 ",
    "Footman level ": "步兵等级 ",
    "Blacksmith level ": "铁匠等级 ",
    "Mana control level ": "法力控制等级 ",
    "Bargaining level ": "讨价还价等级 ",
    "Mage level ": "法师等级 ",
    "Evil control level ": "邪恶控制等级 ",
    "Chairman level ": "会长等级 ",
    "Dark influence level ": "邪恶势力等级 ",
    "Time warping level ": "时间扭曲等级 ",
    "Wizard level ": "巫师等级 ",
    "Student level ": "学生等级 ",
    "Master wizard level ": "精灵法师等级 ",
    "Intimidation level ": "威胁等级 ",
    "Legendary knight level ": "传奇骑士等级 ",
    "Immortality level ": "永生等级 ",
    "Demon training level ": "魔鬼训练等级 ",
    "Apprentice mage level ": "学徒法师等级 ",
    "Cost growth:": "成本成长:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加多空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^x([\d\.]+) Evil gain$/, 'x$1 邪恶收益'],
    [/^x([\d\.]+) Longer lifespan$/, 'x$1 更长的寿命'],
    [/^x([\d\.]+) Military pay$/, 'x$1 军费'],
    [/^x([\d\.]+) Gamespeed$/, 'x$1 游戏速度'],
    [/^x([\d\.]+) Job pay$/, 'x$1 工资'],
    [/^x([\d\.]+) T.A.A. xp$/, 'x$1 奥术协会经验'],
    [/^x([\d\.]+) Magic xp$/, 'x$1 魔法经验'],
    [/^x([\d\.]+) Chairman xp$/, 'x$1 主席经验'],
    [/^x([\d\.]+) Magical xp$/, 'x$1 魔法经验'],
    [/^x([\d\.]+) Merchant pay$/, 'x$1 商人支付'],
    [/^x([\d\.]+) Farm upgrade$/, 'x$1 农场升级'],
    [/^x([\d\.]+) Blacksmith upgrade$/, 'x$1 铁匠升级'],
    [/^x([\d\.]+) Merchant upgrade$/, 'x$1 商人升级'],
    [/^x([\d\.]+) Fishing upgrade$/, 'x$1 钓鱼升级'],
    [/^x([\d\.]+) Mining upgrade$/, 'x$1 挖矿升级'],
    [/^x([\d\.]+) Discovery xp$/, 'x$1 发现经验'],
    [/^x([\d\.]+) Skill xp$/, 'x$1 技能经验'],
    [/^x([\d\.]+) Strength xp$/, 'x$1 力量经验'],
    [/^x([\d\.]+) Military xp$/, 'x$1 军队经验'],
    [/^x([\d\.]+) Job xp$/, 'x$1 工作经验'],
    [/^x([\d\.]+) Expenses$/, 'x$1 费用'],
    [/^x([\d\.]+) Happiness$/, 'x$1 幸福'],
    [/^x([\d\.]+) All xp$/, 'x$1 全部经验'],
    [/^(.+), Meditation level (.+), Productivity level (.+)$/, '$1，冥想等级 $2，生产力等级 $3'],
    [/^(.+), Novel Knowledge level (.+)$/, '$1，新知识 $2'],
    [/^If you decide to embrace evil, all of your levels, coins and even max levels will be reset.\n(.+)You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain$/, '如果你决定接受邪恶，那么你所有的关卡、金币甚至最高关卡都将被重置。你将以崭新的面貌重生。然而，你将解锁一个新的技能线和获得'],
    [/^Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n(.+)A mouth emerges from its surface and begins to cackle, and proceeds to say\: "So you've made it this far... Are you ready to embrace evil\?"$/, '你的直觉是对的。当你到达200岁的时候，你会听到护身符发出不祥的嗡嗡声。一张嘴从它的表面露出来，咯咯地笑着说\:“你已经走到这一步了……你准备好迎接邪恶了吗\?”'],
    [/^You stumble across a strange looking amulet on your 25th birthday. It does not look like\n(.+)it has any worth on the market given that it's made from cheap-looking copper. However, you\n(.+)feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.$/, '你在25岁生日时偶然发现了一个奇怪的护身符。它看起来不像在市场上有任何价值，因为它是由看起来很便宜的铜制成的。然而，你有一种奇怪的冲动想要保存这个护身符，所以你把它放进口袋里妥善保管。'],
    [/^Concentration level (.+)\/(.+), Meditation level (.+)\/$/, '专注等级 $1\/$2，冥想等级 $3\/'],
    [/^On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n(.+)amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n(.+)you realise you do not have many years to live left anyway so you consider touching the eye\n(.+)to see what happens.$/, '在你65岁生日时，你再次遇到奇怪的，无法解释的颤抖从你的护身符。但这一次，一个活生生的眼球从中心出现了。尽管非常害怕，你意识到你已经没有多少年可以活了，所以你考虑触摸一下眼睛，看看会发生什么。'],
    [/^([\d\.]+)\/([\d\.]+), Veteran footman level (.+)\/$/, '$1\/$2, 资深步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Blacksmith level (.+)\/$/, '$1\/$2, 铁匠等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Immortality level (.+)\/$/, '$1\/$2, 永生等级 $3\/'],
    [/^([\d\.]+)\/(.+), Mage level (.+)\/$/, '$1\/$2, 法师等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Footman level (.+)\/$/, '$1\/$2, 步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Veteran knight level (.+)\/$/, '$1\/$2, 资深骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Mana control level (.+)\/$/, '$1\/$2, 法力控制等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Battle tactics level (.+)\/$/, '$1\/$2, 战斗战术等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Holy knight level (.+)\/$/, '$1\/$2, 圣骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Apprentice mage level (.+)\/$/, '$1\/$2, 学徒法师等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Elite knight level (.+)\/$/, '$1\/$2, 精英骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Student level (.+)\/$/, '$1\/$2, 学生等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Knight level (.+)\/$/, '$1\/$2, 骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Miner level (.+)\/$/, '$1\/$2, 矿工等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Fisherman level (.+)\/$/, '$1\/$2, 渔夫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Strength level (.+)\/$/, '$1\/$2, 力量等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Dark influence level (.+)\/$/, '$1k\/$2k, 邪恶势力等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Wizard level (.+)\/$/, '$1k\/$2k, 巫师等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Chairman level (.+)\/$/, '$1k\/$2k, 会长等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Evil control level (.+)\/$/, '$1k\/$2k, 邪恶控制等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Intimidation level (.+)\/$/, '$1k\/$2k, 威胁等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Time warping level (.+)\/$/, '$1k\/$2k, 时间扭曲等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Productivity level (\d+)\/$/, '$1\/$2, 生产力等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Squire level (\d+)\/$/, '$1\/$2, 护卫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Meditation level (\d+)\/$/, '$1\/$2, 冥想等级 $3\/'],
    [/^([\d\.]+) \+ the max level of the skill or job \/ (\d+).$/, '$1 \+ 你的技能或工作的最高等级 \/ $2。'],
    [/^On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n(.+)out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n(.+)a strange etching on the centre of the amulet.$/, '在你45岁生日的时候，你感觉到你口袋里的护身符在不受控制地颤抖。你把它拿出来，不停的颤抖突然停止了。更让你惊讶的是，你会注意到↵这个护身符的中心有一个奇怪的蚀刻。'],
    [/^By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n(.+)However, you will gain$/, '通过触摸眼球，你将获得重生，你将会失去所有等级和金币。然而,你会得到'],
    [/^法力控制等级 (.+)，战斗战术等级 (.+), Holy knight level (.+)\/$/, '法力控制等级 $1，战斗战术等级 $2, 圣骑士等级 $3\/'],
    [/^Mana control level (\d+)\/(\d+), Student level (\d+)\/$/, '法力控制等级 $1\/$2，学生等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Knight level (\d+)\/$/, '战斗战术等级 $1\/$2，骑士等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Footman level (\d+)\/$/, '战斗战术等级 $1\/$2，步兵等级 $3\/'],
    [/^Bargaining level (\d+)\/(\d+), Blacksmith level (\d+)\/$/, '议价等级 $1\/$2，铁匠等级 $3\/'],
    [/^(\d+)\/(\d+), Battle tactics level (.+)\/$/, '$1/$2，战斗战术等级 $3\/'],
    [/^(\d+)\/(\d+), Mage level (.+)\/$/, '$1/$2，法师等级 $3\/'],
    [/^(\d+)\/(\d+)k, Chairman level (.+)\/$/, '$1/$2k，会长等级 $3\/'],
    [/^(\d+)\/(.+), Battle tactics level (.+), Holy knight level (.+)\/$/, '$1/$2，战斗战术等级 $3，圣骑士等级 $4\/'],
    [/^(\d+) evil$/, '$1 邪恶'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);